# Generated by Django 5.0.6 on 2024-06-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
